services:
  api :
    container_name: nfc-entry-management-api-development
    image: nfc-entry-management-api-development:latest
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./api/src:/app
    ports :
      - "8080:8080"
    tty: true

  mysql:
    container_name: nfc-entry-management-mysql
    image: nfc-entry-management-mysql:latest
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - ./mysql/.env.mysql
